# This file maps profile filenames (excluding .toml)
# to names as it appears in the UI drop down menus

[machine_profiles]

cura_default = "Cura Default"

[print_profiles]

cura_default = "Cura Default"